### ISSUE TITLE
Unable to play

### ISSUE THREAD

**Issue by TylerKweskin** [Michael2-3B/Iso-Render#1]
Hey, as the title says I am unable to play the ISO.8xp on my TI-84 plus ce it is saying "Memory is insufficent to preform the calculation. Check infinite recursions or loops. Ex: Y1=Y1" (I got rid of all other programs already)

**Comment by commandz0** [comment]
~~Make sure that you have enough free memory to load the program. You can check which variables are using a lot of memory by pressing 2nd + mem > Mem Management/Delete > All. Look for any large variables that don't have an * next to them. You can move a program out of memory and into the archive by pressing Enter on it, or just delete it if you aren't using it by pressing del.~~

**Comment by commandz0** [comment]
Ignore my previous comment; Michael added this to the Cemetech thread for the project:
> As of August 28, 2023, this program is NOT FUNCTIONAL; you will get a memory error trying to run it. I am unable to fix it for the time being, and have not worked on the project for a long while. Please do not ask when it will be fixed, and please do not make GitHub issues. I am aware of the problem, I just do not have time right now.

**Comment by Michael2-3B** [comment]
Please refer to this post for a working download of the game: https://www.cemetech.net/forum/viewtopic.php?p=303575#303575

When you send it to the calculator, make sure to send it to the archive, not RAM.

And if by chance it still doesn't work for you, you will need to make sure you have enough RAM, by performing a RAM clear. Before you do that, you will want to make sure that all important files you want to keep are in the archive, denoted by a * next to the name in the memory. From the home screen, hit [2nd], [+], Men Management/Delete..., All, and you will see the list. You can archive/unarchive something by hitting enter on it. To clear RAM from the home screen, hit [2nd], [+], Reset, All RAM, Reset.

Do note that the latest working version does not contain redstone.
